name: Unity Build and Distribute (Android Only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Unity Project (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Cache Unity Library
        uses: actions/cache@v4.2.0
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Unity のライセンス認証（UNITY_LICENSE は Secrets に登録済みとする）
      - name: Activate Unity License
        run: echo "${{ secrets.UNITY_LICENSE }}" | base64 --decode > unity.ulf

      # Android 用 APK ビルド
      - name: Build Android APK
        uses: game-ci/unity-builder@v4.3.0
        with:
          targetPlatform: Android
          buildsPath: Build/Android
          unityLicenseFile: unity.ulf

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.6.1
        with:
          name: builds
          path: Build/Android/*.apk

  deploy:
    name: Distribute Android APK via Firebase App Distribution
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: builds

      # Firebase CLI (docker版) を利用して APK をアップロード
      - name: Deploy Android APK via Firebase
        uses: docker://w9jds/firebase-action:master
        with:
          args: "appdistribution:distribute $(find Build/Android -name '*.apk') --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} --groups 'testers' --release-notes 'Automated build release from GitHub Actions'"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
