name: Unity Build and Distribute (Android Only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unity Project (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      
      # ディスク容量の確保: スワップ無効化と不要ツール削除
      - name: Free disk space
        run: |
          # スワップ領域を無効化して削除（約4GB解放）
          sudo swapoff -a && sudo rm -f /swapfile
          # .NET SDK を削除（約2GB解放）
          sudo rm -rf /usr/share/dotnet
          # Haskell (GHC) を削除（約5GB解放）
          sudo rm -rf /opt/ghc /usr/local/.ghcup
          # Google Cloud SDK (google-cloud-cli) を削除
          sudo apt-get remove -y google-cloud-cli || sudo apt-get remove -y google-cloud-sdk
          sudo apt-get autoremove -y && sudo apt-get clean
          # 未使用の Docker イメージやコンテナを削除
          docker system prune -af
          # 空き容量の表示（デバッグ用）
          df -h
        
      - name: Clean up Docker space (with volumes)
        run: docker system prune --volumes -a -f

      - name: Cache Unity Library
        uses: actions/cache@v4.2.0
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Run the build for Android
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          buildsPath: Build/Android
          unityVersion: '6000.0.38f1'

      - name: Upload the Build for Android
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Build-Android
          path: Build/Android/*.apk

  deploy:
    name: Distribute Android APK via Firebase App Distribution
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.9
        with:
          name: Build-Android

      - name: Deploy Android APK via Firebase
        uses: w9jds/firebase-action@v13.32.0
        with:
          args: "appdistribution:distribute $(find Build/Android -name '*.apk') --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} --groups 'testers' --release-notes 'Automated build release from GitHub Actions'"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
