name: Unity Build and Distribute (Android Only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unity Project (Android)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      # ディスク容量の確保
      - name: Free disk space
        run: |
          sudo swapoff -a && sudo rm -f /swapfile
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc /usr/local/.ghcup
          sudo apt-get remove -y google-cloud-cli || sudo apt-get remove -y google-cloud-sdk
          sudo apt-get autoremove -y && sudo apt-get clean
          docker system prune -af
          df -h

      - name: Clean up Docker space (with volumes)
        run: docker system prune --volumes -a -f

      - name: Cache Unity Library
        uses: actions/cache@v4.2.0
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run the build for Android
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android           # ビルド対象プラットフォーム
          buildsPath: build                 # 出力フォルダ（小文字の "build" を使用）
          buildName: MyAndroidApp           # ビルド名（生成されるファイル名は MyAndroidApp.apk）
          androidExportType: androidPackage # 出力形式: APKをビルド
          unityVersion: '6000.0.38f1'       # 実際のUnityバージョンに合わせて変更

      - name: Upload the Build for Android
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Build-Android
          path: build/Android/MyAndroidApp.apk

      - name: Install Ruby & set up Bundler 2.4.x in user-land
        run: |
          # 1) Ensure Ruby is installed (2.7 on ubuntu-20.04)
          sudo apt-get update
          sudo apt-get install -y ruby-full

          # 2) Remove any system-wide Bundler that might conflict
          #    (エラーになっても続行するよう "|| true" つける)
          sudo gem uninstall --all bundler || true

          # 3) Bundler 2.4.x 系をユーザー領域 (~/.gem/ruby/2.7.0) にインストール
          gem install bundler -v 2.4.22 --user-install

          # 4) GitHub Actions の次ステップでも bundler コマンドが使えるようPATHを通す
          echo "GEM_HOME=$(ruby -r rubygems -e 'puts Gem.user_dir')" >> $GITHUB_ENV
          echo "PATH=$(ruby -r rubygems -e 'puts Gem.user_dir')/bin:$PATH" >> $GITHUB_ENV

      - name: Prepare Gemfile
        run: |
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'fastlane'" >> Gemfile
          echo "gem 'fastlane-plugin-firebase_app_distribution'" >> Gemfile

      - name: Bundle install (with Bundler 2.4.x)
        run: |
          # `_2.4.22_` を付けることで、明示的に Bundler 2.4.22 を使用
          bundle _2.4.22_ install --path vendor/bundle

      - name: Setup Service Account
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > service_account.json

      - name: Install Google Cloud SDK & Firebase CLI
        run: |
          # 1) 前準備: 必要ツールのインストール
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates gnupg curl
          
          # 2) Google公式のリポジトリ情報を追加
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
            | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          
          # 3) GoogleのGPGキーを取得 & 登録
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
            | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          
          # 4) リポジトリ更新
          sudo apt-get update
          
          # 5) Google Cloud CLI (google-cloud-cli) + Firebase CLI (google-cloud-cli-firebase) を同時にインストール
          sudo apt-get install -y google-cloud-cli google-cloud-cli-firebase
          
          # 6) 確認 (オプション)
          gcloud --version
          which gcloud

    
      - name: Distribute to Firebase App Distribution
        run: |
          bundle _2.4.22_ exec fastlane run firebase_app_distribution \
            apk_path:"build/Android/MyAndroidApp.apk" \
            app:"${{ secrets.FIREBASE_ANDROID_APP_ID }}" \
            service_credentials_file:"service_account.json" \
            release_notes:"Release from GitHub Actions" \
            groups:"testers"

