name: Unity Build and Distribute (Android Only)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unity Project (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      
      # ディスク容量の確保: スワップ無効化と不要ツール削除
      - name: Free disk space
        run: |
          sudo swapoff -a && sudo rm -f /swapfile
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc /usr/local/.ghcup
          sudo apt-get remove -y google-cloud-cli || sudo apt-get remove -y google-cloud-sdk
          sudo apt-get autoremove -y && sudo apt-get clean
          docker system prune -af
          df -h

      - name: Clean up Docker space (with volumes)
        run: docker system prune --volumes -a -f

      - name: Cache Unity Library
        uses: actions/cache@v4.2.0
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run the build for Android
        uses: game-ci/unity-builder@v4.3.0
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android           # ビルド対象プラットフォーム
          buildsPath: build                 # 成果物を出力するフォルダ（デフォルト "build"）
          buildName: MyAndroidApp           # ビルド名（出力APK/AABのファイル名ベース）
          androidExportType: androidPackage # 出力形式: APKをビルド（省略可、デフォルトがapk）

      - name: Debug List build output
        run: ls -R build

      - name: Upload the Build for Android
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Build-Android
          # ディレクトリ全体をアップロード（後で deploy ジョブで中身を確認可能）
          path: build/Android/MyAndroidApp.apk
  
  deploy:
    name: Distribute Android APK via Firebase App Distribution
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Download Build Artifact
        uses: actions/download-artifact@v4.1.9
        with:
          name: Build-Android

      # デバッグ用: アップロードされたファイル一覧を表示
      - name: List downloaded artifact files
        run: |
          find . -type f

      - name: Deploy Android APK via Firebase
        uses: w9jds/firebase-action@v13.32.0
        with:
          args: "appdistribution:distribute $(find Build/Android/MyAndroidApp -name '*.apk') --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} --groups 'testers' --release-notes 'Automated build release from GitHub Actions'"
        env:
          # 最新の認証方法として GCP_SA_KEY を利用する場合：
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
